# Authentication information
TWITTER_CONSUMER_KEY = 'PUT HERE YOUR API KEY'
TWITTER_CONSUMER_SECRET = 'PUT HERE YOUR API SECRET'

TWITTER_ACCESS_TOKEN = 'PUT HERE YOUR ACCESS TOKEN'
TWITTER_ACCESS_TOKEN_SECRET = 'PUT HERE YOUR SECRET TOKEN'
